---
title: "Exploring Potential Influencers of Math Student Performance"
author: "Lauren Duvall, Shikyna William, Thomas Linden"
date: "`r Sys.Date()`"
lang: en
output: 
  html_document:
    theme: paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressMessages(library(dplyr))    # Data manipulation
suppressMessages(library(ggplot2))  # Plotting
suppressMessages(library(plotly))  # Plotting
suppressMessages(library(readr))    # Reading the dataset
suppressMessages(library(knitr))    # For clean tables
```

[Kaggle Link](https://www.kaggle.com/datasets/adilshamim8/math-students/data)

## Introduction

This dataset

___

## Load Packages
```{r}
library(dplyr)
library(plotly)
```

___

## Data Cleaning
```{r}
raw <- read.csv("Math-Students.csv")
#Rename cols, convert factors for summary, transmute to drop old columns
formatted <- raw %>% transmute(
  
)
summary(formatted)
```

___

## Exploratory Data Analysis
```{r}
#Make correlation table
cor_df <- formatted %>% select(where(is.numeric)) %>% cor(use = "complete.obs") %>% 
  as.table() %>% as.data.frame()

colnames(cor_df) <- c("Var1", "Var2", "Correlation")

cor_df %>% ggplot(aes(Var1, Var2, fill = Correlation)) + 
  geom_tile(color = 'white') + 
  scale_fill_gradient2(low = '#067bc2', mid = 'white', high = '#fe4a49', 
                       midpoint = 0, limit = c(-1,1), name = 'Correlation') +
  labs(title = "Correlation Heatmap", x = '', y = '') + 
  theme_minimal() + 
  coord_fixed() + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
```

**Intuitive relationships:** 



**Some relationships to look into more:**



**Unintuitive relationships:** 



**Features not in the correlation heatmap:** 

___

## Plot 1
```{r}

```

## Plot 2

## Plot 3

## Plot 4

## Plot 5

___

## Conclusions

### Limitations:

### Future Steps:

___

## References:
> 